apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  #annotations:
  #  nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - host: mywebserver.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websrvc
            port:
              number: 8080