apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-11-23T10:04:06Z"
  name: websrvc
  namespace: default
  resourceVersion: "43251"
  uid: a7d8a2fe-3f9b-447a-859e-6b7718da316d
spec:
  clusterIP: 10.104.101.149
  clusterIPs:
  - 10.104.101.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    server: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
